# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest
  name: Default
  demands:
     - Agent.Name -equals my-peronal-agent
   

steps:
- task: Maven@3
  inputs:
    mavenPomFile: '$(system.defaultWorkingDirectory)/spring-app/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(52bf95d5-234b-47ac-8bb7-cda36aee5e5e)'
    appType: 'webApp'
    WebAppName: 'azure-spring-app-service'
    deployToSlotOrASE: true
    ResourceGroupName: 'azure-spring-app-group'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/spring-app-0.0.1-SNAPSHOT.jar'
    WebConfigParameters: 'java'
